### ISSUE TITLE
RuntimeError: Trying to resize storage that is not resizable

### ISSUE THREAD

**Issue by biochem-fan** [3dem/DynaMight#1]
My first test of DynaMight crashed as follows:

```
Training on GPU 0
Initializing the particle dataset
Assigning a diameter of 179 angstrom
Number of particles: 57080
Initialized data loaders for half sets of size 25686  and  25686
box size: 128 pixel_size: 1.55625 virtual pixel_size: 0.007751937984496124  dimension of latent space:  5
Number of used gaussians: 30000
Optimizing scale only
Initializing gaussian positions from reference
100%|##########| 50/50 [00:03<00:00, 15.83it/s]
Final error: 5.638866059598513e-05
Optimizing scale only
Initializing gaussian positions from reference
100%|##########| 50/50 [00:02<00:00, 19.66it/s]
Final error: 5.638863149215467e-05
consensus gaussian models initialized
Number of flexible points: 26439
Number of flexible points: 26439
consensus model  initialization finished
mean distance in graph for half 1: 1.1061224937438965 Angstrom ;This distance is also used to construct the initial graph 
mean distance in graph for half 2: 1.1061224937438965 Angstrom ;This distance is also used to construct the initial graph 
Computing half-set indices
Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home1/app/.conda/envs/relion-5.0/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home1/app/.conda/envs/relion-5.0/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home1/app/.conda/envs/relion-5.0/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home1/app/.conda/envs/relion-5.0/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 127, in collate
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/home1/app/.conda/envs/relion-5.0/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 127, in <dictcomp>
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/home1/app/.conda/envs/relion-5.0/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home1/app/.conda/envs/relion-5.0/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 161, in collate_tensor_fn
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
RuntimeError: Trying to resize storage that is not resizable
```
I also see the following warning:
```
/home1/app/.conda/envs/relion-5.0/lib/python3.10/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
```

The command line is:
```
`which relion_python_dynamight` optimize-deformations  --refinement-star-file Refine3D/job050/run_data.star --output-directory DynaMight/job055/ --initial-model Refine3D/job050/run_class001.mrc --n-gaussians 30000 --regularization-factor 1 --n-threads 32 --preload-images  --mask-file MaskCreate/job048/mask.mrc --gpu-id 0
```

My environment is
- Ubuntu 20.04 LTS
- NVIDIA P100 x 4
- 256 GB RAM
- DynaMight installed automatically by RELION's `cmake`
- Box size: 128 px
- Pixel size: 1.556 Å/px
- Number of particles: 57080

**Comment by biochem-fan** [comment]
I confirmed all jobs completed fine after your fix. Thank you very much!
